//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlowLearnerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppId { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LevelNo { get; set; }
    }
}
