//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlowLearnerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int CollectionId { get; set; }
        public string CollectionType { get; set; }
        public string CollectionText { get; set; }
        public string CollectionImage { get; set; }
        public Nullable<int> DoctorId { get; set; }
    }
}
