//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlowLearnerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientWord
    {
        public int PatientWordId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> WordId { get; set; }
    }
}
