//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlowLearnerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserGender { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> ReferenceUserId { get; set; }
    }
}
