//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlowLearnerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int WordId { get; set; }
        public string WordText { get; set; }
        public string ImagePath { get; set; }
        public string WordCategory { get; set; }
        public Nullable<int> WordLevel { get; set; }
    }
}
